<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZndsklb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZndsklb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZndsklb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZndsklb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZndsklb\appProdProjectContainer([
    'container.build_hash' => 'Zndsklb',
    'container.build_id' => '7b3ff63e',
    'container.build_time' => 1671686225,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZndsklb');
